include_recipe "sprout-osx-apps::1password"
include_recipe "sprout-osx-apps::chrome"
include_recipe "sprout-osx-apps::evernote"
include_recipe "sprout-osx-apps::flowdock"
include_recipe "sprout-osx-apps::flux"
include_recipe "sprout-osx-apps::go"
include_recipe "sprout-osx-apps::google_drive"
include_recipe "sprout-osx-apps::google_voice_and_video"
include_recipe "sprout-osx-apps::intellij_ultimate_edition"
include_recipe "sprout-osx-apps::iterm2"
# include_recipe "sprout-osx-apps::java"
# include_recipe "sprout-osx-apps::maven"
# include_recipe "sprout-osx-apps::node_js"
include_recipe "sprout-osx-apps::p7zip"
# include_recipe "sprout-osx-apps::pg_admin"
# include_recipe "sprout-osx-apps::phantomjs"
# include_recipe "sprout-osx-apps::python"
# include_recipe "sprout-osx-apps::qt"
include_recipe "sprout-osx-apps::remote_desktop"
include_recipe "sprout-osx-apps::skype"
include_recipe "sprout-osx-apps::sourcetree"
include_recipe "sprout-osx-apps::sublime_text"
include_recipe "sprout-osx-apps::vagrant"
include_recipe "sprout-osx-apps::vagrant_plugins"
include_recipe "sprout-osx-apps::virtualbox"
# include_recipe "sprout-osx-apps::xquartz"
# include_recipe "sprout-osx-apps::zsh"
