include_recipe "sprout-osx-settings::defaults_fast_key_repeat_rate"
include_recipe "sprout-osx-settings::finder_display_full_path"
include_recipe "sprout-osx-settings::function_keys"
include_recipe "sprout-osx-settings::global_environment_variables"
include_recipe "sprout-osx-settings::input_on_login"
include_recipe "sprout-osx-settings::inputrc"
include_recipe "sprout-osx-settings::keyboard"
include_recipe "sprout-osx-settings::locate"
# don't auto-set machine name
# include_recipe "sprout-osx-settings::machine_name"
include_recipe "sprout-osx-settings::menubar"
include_recipe "sprout-osx-settings::osx_disable_natural_scrolling"
include_recipe "sprout-osx-settings::osx_aqua_color_preferences"
include_recipe "sprout-osx-settings::remove_garageband"
# include_recipe "sprout-osx-settings::screensaver"
include_recipe "sprout-osx-settings::screen_sharing"
include_recipe "sprout-osx-settings::screen_sharing_app"
include_recipe "sprout-osx-settings::set_menubar_clock_format"
include_recipe "sprout-osx-settings::shared_memory"
include_recipe "sprout-osx-settings::set_finder_show_all_hd_on_desktop"
include_recipe "sprout-osx-settings::set_finder_show_user_home_in_sidebar"
include_recipe "sprout-osx-settings::set_multitouch_preferences"
include_recipe "sprout-osx-settings::snmpd"
include_recipe "sprout-osx-settings::sshd_on"
include_recipe "sprout-osx-settings::tcp_keepalive"
include_recipe "sprout-osx-settings::terminal_preferences"
include_recipe "sprout-osx-settings::timemachine"
include_recipe "sprout-osx-settings::updates"
