name             'malston'
maintainer       'Mark Alston'
maintainer_email 'malston@pivotal.io'
license          'MIT'
description      'Personalized recipes for my OSX workstation'
long_description 'Personalized recipes for my OSX workstation to use with pivotal-sprout/sprout-wrap.'
version          '0.1.0'
supports         'mac_os_x'

depends          'sprout-base'
depends          'homebrew'
depends          'sprout-osx-settings'
depends          'sprout-osx-apps'
