name             'malston'
maintainer       'PivotalServices.io'
maintainer_email 'malston@pivotal.io'
license          'MIT'
description      'PivotalServices stuff'
long_description 'Stuff'
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
depends          'sprout-osx-settings'
